config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "static_pages#home"

  get "users/new", to: "users#new", as: "new_users"
  post "users", to: "users#submit", as: "submit_users"

  get "games/result/:user_id", to: "search_games#search", as: "result"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :birth_date, presence: true
  validates :name, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_games_controller.rb
class SearchGamesController < ApplicationController
  def search
    @user = User.find(params[:user_id])
    @birth_date = @user.birth_date.strftime("%Y-%m-%d")

    response = HTTParty.get("https://api.rawg.io/api/games", {
      query: {
        key: ENV["RAWG_API_KEY"],
        dates: "#{@birth_date},#{@birth_date}",
        page_size: 1
      },
      headers: { "Cache-Control" => "no-cache" }
    })

    game_data = response.parsed_response["results"]&.first
    @game = game_data
    @genres = game_data["genres"].map { |genre| genre["name"] } if game_data.present?

    render :result
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def submit
    @user = User.find_by(name: user_params[:name])

    if @user
      if @user.update(user_params)
        redirect_to result_path(user_id: @user.id)
      else
        redirect_to new_users_path
      end
    else
      @user = User.new(user_params)
      if @user.save
        redirect_to result_path(user_id: @user.id)
      else
        redirect_to new_users_path
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :birth_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: "Your Birth Game",
      title: "Your Birth Game",
      reverse: true,
      charset: "utf-8",
      description: "あなたの誕生日に発売されたゲームは何かな？",
      canonical: request.original_url,
    og: {
      site_name: "Your Birth Game",
      title: "Your Birth Game",
      description: "あなたの誕生日に発売されたゲームは何かな？",
      type: "website",
      url: request.original_url,
      image: image_url("YourBirthGame.png"),
      locale: "ja_JP"
    },
    twitter: {
      card: "summary_large_image",
      title: "Your Birth Game",
      description: "あなたの誕生日に発売されたゲームは何かな？",
      image: image_url("YourBirthGame.png")
    } }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "YourBirthGame" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <%= favicon_link_tag("favicon.ico") %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script src="https://kit.fontawesome.com/ed5990692e.js" crossorigin="anonymous"></script>
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <body>
    <header class="bg-yellow-400 h-12 text-white text-2xl flex items-center">
      <%= link_to "YourBirthGame", root_path, class: "text-left ml-4" %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/search_games/result.html.erb
<body>
  <div class="text-center my-8">
    <p>誕生日: <%= @birth_date %></p>
    <% if @game.present? %>
      <p class="text-xl"><%= @user.name %>が生まれた日にリリースされたゲームは…</p>
      <h2 class="text-6xl text-red-300"><%= @game['name'] %></h2>
      <p class="text-2xl">ジャンル： <%= @genres.join(", ") %></p>
      <p class="text-xl">でした！！</p>
      <div class="grid place-items-center my-4">
        <%= image_tag "#{@game['background_image']}", height: "300", width: "400" %>
      </div>
      <%= link_to "https://twitter.com/share?url=#{request.url}&text=私の誕生日と同じ発売日のゲームは#{@game['name']}でした!!%0a%23YourBirthGame_m%0a",
        target: '_blank',
        class: "btn btn-outline inline-flex items-center space-x-2" do %>
        <i class="fa-brands fa-x-twitter inline-block hover:text-white"></i>シェア
      <% end %><br>
      <%= link_to "トップに戻る", root_path, class: "btn btn-wide bg-yellow-400 hover:bg-red-300 text-white text-xl my-3" %>
    <% else %>
      <p class="mt-3 text-4xl text-red-300">ゲームが見つかりませんでした…</p>
      <p class="my-3 text-xl">年を変えて再検索してみてね</p>
      <%= link_to "もう一回", new_users_path, class: "btn btn-wide bg-yellow-400 hover:bg-red-300 text-white text-xl my-3" %><br>
      <%= link_to "トップに戻る", root_path, class: "btn btn-wide bg-yellow-400 hover:bg-red-300 text-white text-xl" %>
    <% end %>
  </div>
</body>

app/views/static_pages/home.html.erb
<div class="text-center">
  <div class="grid place-items-center">
    <%= image_tag 'YourBirthGame.png', height: '300', width: '300' %>
  </div>
  <h1 class="font-bold text-red-300 text-6xl my-4">Your Birth Game</h1>
  <p class="text-2xl">あなたの誕生日と同じ発売日のゲームは何かな？</p>
    <%= link_to "スタート", new_users_path, class: "btn btn-wide bg-yellow-400 hover:bg-red-300 text-white text-xl my-8" %>
</div>

app/views/users/new.html.erb
<body>
  <%= form_with(scope: :user, url: submit_users_path, method: :post) do |f| %>
  <div class="flex justify-center">
    <div class="card bg-red-300 w-600 min-w-min my-10">
      <div class="card-body items-center text-center">
        <h1 class="card-title text-white text-3xl">あなたの名前と誕生日を入力してね！</h1>
          <div class="text-2xl text-white my-6">
            <%= f.label :name, "名前" %><br>
            <%= f.text_field :name, class: "input input-bordered input-warning w-full max-w-xs mt-3 text-black" %><br>
          </div>
          <div class="text-white my-6">
            <%= f.label :birth_date, "誕生日(年/月/日)", class: "text-2xl" %><br>
            <p>※近年の方が検索結果が出やすいよ！</p>
            <%= f.date_select :birth_date, { start_year: 1950, end_year: 2024, use_two_digit_numbers: true },
              class: "select select-warning max-w-xs text-black mt-3" %><br>
          </div>
          <div class="card-action">
            <%= f.submit "検索する", class: "btn btn-wide bg-yellow-400 hover:bg-yellow-200 text-white text-xl my-6" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</body>